from django.db import models

# Create your models here.
class Personal_Details(models.Model):
    student_id = models.CharField(max_length=200)
    Aname = models.CharField(max_length=150)
    name = models.CharField(max_length=100)
    Adate =  models.CharField(max_length=300)
    division = models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    db_birth = models.CharField(max_length=300)
    age = models.CharField(max_length=300)
    nationality = models.CharField(max_length=300)
    religion = models.CharField(max_length=200)
    cast = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    sylubus = models.CharField(max_length=200)
    tongues = models.CharField(max_length=200)
    id_marks = models.CharField(max_length=200)

class Prant_Details(models.Model):
    Ad_Number = models.CharField(max_length=200)
    Parent_Name = models.CharField(max_length=200)
    relation = models.CharField(max_length=250)
    Parent_Occ = models.CharField(max_length=200)
    Parent_Add = models.CharField(max_length=200)
    tele_number = models.CharField(max_length=100)
    G_name = models.CharField(max_length=200)
    G_address = models.CharField(max_length=200)
    G_tele_number = models.CharField(max_length=100)
    Prant_Mobile_num = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    G_Mobile_num = models.CharField(max_length=100)
    Pincode = models.CharField(max_length=100)
    Income = models.CharField(max_length=300)
    Parent_ID = models.CharField(max_length=200)

class PUPIL_Details(models.Model):
    Rg_Number = models.CharField(max_length=250)
    Adate = models.CharField(max_length=250)
    Yumedium = models.CharField(max_length=250)
    Lschool = models.CharField(max_length=250)
    Lstandard = models.CharField(max_length=250)
    Lmedium = models.CharField(max_length=250)
    LDate_Admission = models.CharField(max_length=250)
    LDate_Leave = models.CharField(max_length=250)
    Transfer_date = models.CharField(max_length=250)
    Remarks = models.CharField(max_length=250)
    mark = models.CharField(max_length=250)
    total_mark = models.CharField(max_length=250)
    ages = models.CharField(max_length=250)