# Generated by Django 4.0.2 on 2023-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionnumber', models.CharField(max_length=20)),
                ('parentname', models.CharField(max_length=30)),
                ('relation', models.CharField(max_length=50)),
                ('permanentaddress', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('guardianname', models.CharField(max_length=120)),
                ('guardianaddres', models.CharField(max_length=120)),
                ('guardiantelephone_number', models.CharField(max_length=50)),
                ('parent_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('guardianmobile_number', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=30)),
                ('income', models.CharField(max_length=100)),
                ('parent_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('AdmnNo', models.CharField(max_length=20)),
                ('ClassCode', models.CharField(max_length=10)),
                ('Tc', models.CharField(max_length=10)),
                ('ClassNo', models.CharField(max_length=20)),
                ('Isconveyance', models.CharField(max_length=20)),
                ('Isdeduction', models.CharField(max_length=20)),
                ('Isbuildingfund', models.CharField(max_length=20)),
                ('Isadmissionfees', models.CharField(max_length=20)),
                ('ACYearValue', models.CharField(max_length=20)),
                ('Photo', models.CharField(max_length=20)),
            ],
        ),
    ]
