# Generated by Django 4.0.2 on 2023-03-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Tc',
        ),
    ]
