# Generated by Django 4.0.2 on 2023-03-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webone', '0003_personal_details_prant_details_delete_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUPIL_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rg_Number', models.CharField(max_length=250)),
                ('Adate', models.CharField(max_length=250)),
                ('Yumedium', models.CharField(max_length=250)),
                ('Lschool', models.CharField(max_length=250)),
                ('Lstandard', models.CharField(max_length=250)),
                ('Lmedium', models.CharField(max_length=250)),
                ('LDate_Admission', models.CharField(max_length=250)),
                ('LDate_Leave', models.CharField(max_length=250)),
                ('Transfer_date', models.CharField(max_length=250)),
                ('Remarks', models.CharField(max_length=250)),
                ('mark', models.CharField(max_length=250)),
                ('total_mark', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
            ],
        ),
    ]
