# Generated by Django 4.0.2 on 2023-03-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webone', '0004_pupil_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil_details',
            old_name='age',
            new_name='ages',
        ),
    ]
