# Generated by Django 4.0.2 on 2023-03-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webone', '0006_rename_pupil_details_webone_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='webone_student',
            new_name='PUPIL_Details',
        ),
    ]
